ARG PYTHON_VERSION=%%PLACEHOLDER%%
ARG ALPINE_VERSION=%%PLACEHOLDER%%

FROM python:${PYTHON_VERSION}-alpine${ALPINE_VERSION}

RUN apk add --no-cache libxml2 libxslt && \
    apk add --no-cache --virtual .build-deps libxml2-dev libxslt-dev g++ && \
    pip install --no-cache-dir beautifulsoup4 lxml && \
    apk del .build-deps
